### ISSUE TITLE
how to completely ignore a module

### ISSUE THREAD

**Issue by flying-sheep** [rollup/rollup-plugin-npm#11]
js-yaml has [a “browser” field](https://github.com/nodeca/js-yaml/blob/6f8eb023441ab84746670910de8dd967b7455144/package.json#L43) in its package.json, which should mean “in the browser environment, import those modules as empty objects”.

that’s their way to say it’s an optional dependency. we should support that.

**Comment by Rich-Harris** [comment]
Have opened #14 which supports the `browser` field, including this.

**Comment by Rich-Harris** [comment]
Forgot to close this – 1.2.0 supports `pkg.browser`
