### ISSUE TITLE
More flexible 'main' option

### ISSUE THREAD

**Issue by callumlocke** [rollup/rollup-plugin-npm#6]
Suggestion: allow the `main` option to be provided as an array.

```js
{
  include: 'node_modules/**',
  jsnext: true,
  main: ['foo', 'bar'] // use main (or index.js) only if the module is in this whitelist
}
```

Reasoning: in general, I want to default to trusting anything with a `jsnext:main` field is probably safe to bundle. But for everything else, I want to default to keeping it external until I've verified it's safe to bundle.

**Comment by Rich-Harris** [comment]
Could you achieve the same thing with `skip`? (I realise it's a blacklist rather than a whitelist – you could flip it with `skip: Object.keys(pkg.dependencies).filter(x => ~whitelist.indexOf(x))` if necessary...)

**Comment by jbach** [comment]
This is a problem for me as well, as manually skipping proves difficult when dependencies that *do* provide `jsnext:main` use dependecies *without* `jsnext:main`. To me it makes sense to automatically skip dependencies that lack the `jsnext:main` property when using `{ jsnext: true, main: false }`?

**Comment by Rich-Harris** [comment]
@jbach what about a `skip: true` option that behaved as you described? If both `jsnext` and `main` were `false`, would skip any external module that didn't have an explicit path (like `foo/lib/thing.js`), and if `jsnext` was `true` but `main` was `false`, would automatically skip all non-`jsnext:main` modules.

**Comment by jbach** [comment]
Yeah, I guess that’d work :+1:

**Comment by Rich-Harris** [comment]
Have opened #16

**Comment by Rich-Harris** [comment]
Finally got round to releasing this, as 1.3.0
